version: '3.4'

services:
  backend:
    container_name: r-factor-website
    build:
      context: ./
      args:
        ENABLE_RECAPTCHA: true
        RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
        RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    ports:
      - 80:8002
