clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  build:
    image: devforth/drone-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - /bin/bash build.sh
    secrets:
      - RECAPTCHA_SITE_KEY
      - RECAPTCHA_SECRET_KEY

  deploy:
    image: devforth/drone-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - /bin/bash deploy.sh

branches: master
